spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/bh_tracker}
    username: ${DB_USERNAME:hyunbin}
    password: ${DB_PASSWORD:}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: true

server:
  port: 8080

logging:
  level:
    com.bh.tracker: INFO
